version: '3'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-gateway
    ports:
      - 8086:8080
    networks:
      - api-gateway
      - service-discovery
      - observability
    environment:
#      ENTERTAINMENT_SERVICE_ADDRESS: entertainment-service:8080,entertainment-service-2:8080
      COVID19_SERVICE_ADDRESS: covid19-service:8080
      TRACER_AGENT_ADDRESS: jaeger-tracing:5775
      CONSUL_AGENT_ADDRESS: consul-server:8500
    depends_on:
      - consul-server

networks:
  api-gateway:
    driver: bridge
  service-discovery:
    external:
      name: service-discovery_service-discovery
  observability:
    external:
      name: observability_observability
